use_frameworks!

target 'LQGPhotoBrowser_Example' do
  pod 'LQGPhotoBrowser', :path => '../'

  target 'LQGPhotoBrowser_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
